version: '3.4'

services:
  visualstudiocredentialexample:
    image: ${DOCKER_REGISTRY-}visualstudiocredentialexample
    build:
      context: .
      dockerfile: VisualStudioCredentialExample/Dockerfile

  functionappisolated:
    image: ${DOCKER_REGISTRY-}functionappisolated
    build:
      context: .
      dockerfile: FunctionAppIsolated/Dockerfile
